#!/usr/bin/env python3

########################################################
# test
# Concatenate problem and test files then run SAT/QBF 
# solver using bule
# 16/01/2021
########################################################

########################################################
# Imports
########################################################

import os
import sys
import re

########################################################
# Globals
########################################################

temp_file = "temp_" + str(hash("temp"))

ground = f'''
echo "\n---------- Solver Output -----------\n"
./bule ground -t=1 -u=0 {temp_file} 2>/dev/null | grep -v '%% Rules:'
'''

file_output = f'''
echo "\n----------- File Output ------------\n"
cat {temp_file}
'''

########################################################
# Logic
########################################################

# Notes: -f/--file => show concatenated file output
#        -g/--ground => show grounded output

# If arguments less than 2 provided, exit
if len(sys.argv) <= 1:
    print("Usage: ./test [flags] FILE_1 ... [OTHER_FILES] ...")
    exit()

# Temporary switches for flags

flag1 = 'echo -n ""'
flag2 = 'echo -n ""'

# Process commandline arguments
files = list()
for i in sys.argv[1:]:
    if i == '-g' or i == '--ground':
        flag2 = ground
    if i == '-f' or i == '--file':
        flag1 = file_output
    if re.search("[-\w//]*\.[-\w//]*", i):
        files.append(i)

# If no valid files given, exit
if len(files) <= 0:
    print("Error: Incorrect number of files given", file=sys.stderr)
    print("Usage: ./test [flags] FILE_1 ... [OTHER_FILES] ...")
    exit()

files = " ".join(files)

os.system(f'''
    cat {files} > solvers/bule/{temp_file}
    cd solvers/bule
    {flag1}
    {flag2}
    echo "\n---------- Result Output -----------\n"
    ./bule solve {temp_file} 2>/dev/null | grep "SAT\|UNSAT"
    echo ""
    rm ./{temp_file}
    cd ..
''')